# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/business_doc',
                'doc_host': 'https://bthek1.github.io',
                'git_url': 'https://github.com/bthek1/business_doc',
                'lib_path': 'business_doc'},
  'syms': {'business_doc.core': {'business_doc.core.foo': ('core.html#foo', 'business_doc/core.py')}}}
